esphome:
  name: esp8266-relay
  friendly_name: ESP8266 Relay

esp8266:
  board: esp01_1m

logger:

api:
  encryption:
    key: !secret esp8266_relay_api_encryption_key

ota:
  password: !secret esp8266_relay_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: !secret esp8266_relay_ap_ssid
    password: !secret esp8266_relay_ap_password

captive_portal:

output:
  - platform: gpio
    pin: GPIO14
    id: output_relay

button:
  - platform: template
    name: "Trigger"
    on_press:
      - output.turn_on: output_relay
      - delay: 500ms
      - output.turn_off: output_relay
  - platform: restart
    name: Restart
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: shutdown
    name: Shutdown

sensor:
  - platform: uptime
    name: Uptime
    update_interval: 60s
  - platform: wifi_signal
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"
  - platform: copy
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""
