substitutions:
  temp_sensor_pin: GPIO17 # D3 - green
  mosi_pin: GPIO23 # D7 - DIN (blue)
  clk_pin: GPIO18 # D5 - CLK (yellow)
  cs_pin: GPIO19 # D6 - CS (orange)
  dc_pin: GPIO21 # D2 - DC (green)
  reset_pin: GPIO22 #D1 - RST (white)

esphome:
  name: esp32-teams-monitor-v2
  friendly_name: ESP32 Teams Monitor v2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esp32_teamsmonitor_api_encryption_key

ota:
  - platform: esphome
    password: !secret esp32_teamsmonitor_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: !secret esp32_teamsmonitor_ip

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret esp32_teamsmonitor_ap_ssid
    password: !secret esp32_teamsmonitor_ap_password

captive_portal:
    
button:
  - platform: restart
    name: Restart
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: shutdown
    name: Shutdown

sensor:

  - platform: dht
    pin: ${temp_sensor_pin}
    temperature:
      id: dht_temperature
      name: "Temperature"
    humidity:
      id: dht_humidity
      name: "Humidity"
    update_interval: 60s

  # Diagnostic

  - platform: uptime
    name: Uptime
    update_interval: 60s

  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    name: "WiFi Signal dB"
    id: wifi_signal_db
    update_interval: 60s
    entity_category: "diagnostic"

  - platform: copy # Reports the WiFi signal strength in %
    source_id: wifi_signal_db
    name: "WiFi Signal Percent"
    filters:
      - lambda: return min(max(2 * (x + 100.0), 0.0), 100.0);
    unit_of_measurement: "%"
    entity_category: "diagnostic"
    device_class: ""

binary_sensor:

  # Andrie template binary sensors
  - platform: homeassistant
    id: andrie_teams_meeting
    entity_id: binary_sensor.andrie_teams_meeting
  - platform: homeassistant
    id: andrie_teams_microphone
    entity_id: binary_sensor.andrie_teams_microphone
  - platform: homeassistant
    id: andrie_teams_video
    entity_id: binary_sensor.andrie_teams_video
  - platform: homeassistant
    id: andrie_teams_sharing
    entity_id: binary_sensor.andrie_teams_sharing
  - platform: homeassistant
    id: andrie_teams_blurred
    entity_id: binary_sensor.andrie_teams_background_blurred
  - platform: homeassistant
    id: andrie_teams_recording
    entity_id: binary_sensor.andrie_teams_recording

  # Rinda template binary sensors
  - platform: homeassistant
    id: rinda_teams_meeting
    entity_id: binary_sensor.rinda_teams_meeting
  - platform: homeassistant
    id: rinda_teams_microphone
    entity_id: binary_sensor.rinda_teams_microphone
  - platform: homeassistant
    id: rinda_teams_video
    entity_id: binary_sensor.rinda_teams_video
  - platform: homeassistant
    id: rinda_teams_sharing
    entity_id: binary_sensor.rinda_teams_sharing
  - platform: homeassistant
    id: rinda_teams_blurred
    entity_id: binary_sensor.rinda_teams_background_blurred
  - platform: homeassistant
    id: rinda_teams_recording
    entity_id: binary_sensor.rinda_teams_recording

# OLED Display 128x128: SSD1327

spi:
  mosi_pin: ${mosi_pin}
  clk_pin: ${clk_pin}

font:
  # gfonts://family[@weight]
  - file: "gfonts://Roboto"
    id: roboto_l
    size: 24
  - file: "gfonts://Roboto"
    id: roboto_s
    size: 16
  
color:
  - id: color_bright
    white: 100%
  - id: color_dimmed
    white: 25%

display:
  - platform: ssd1327_spi
    model: "SSD1327 128x128"
    cs_pin: ${cs_pin}
    dc_pin: ${dc_pin}
    reset_pin: ${reset_pin}
    brightness: 100%
    rotation: 270

    # Horizontal rows    
    # lambda: |-
    #   // Andrie header
    #   it.printf(0, 0, id(roboto_s), "Andrie");

    #   // Andrie icons
    #   it.image(0, 24, id(andrie_teams_meeting).state ? icon_phone : icon_phone_off, id(andrie_teams_meeting).state ? id(color_bright) : id(color_dimmed));
    #   it.image(32, 24, id(andrie_teams_microphone).state ? icon_microphone : icon_microphone_off, id(andrie_teams_microphone).state ? id(color_bright) : id(color_dimmed));
    #   it.image(64, 24, id(andrie_teams_video).state ? icon_webcam : icon_webcam_off, id(andrie_teams_video).state ? id(color_bright) : id(color_dimmed));
    #   it.image(96, 24, id(andrie_teams_sharing).state ? icon_projector_screen : icon_projector_screen_off, id(andrie_teams_sharing).state ? id(color_bright) : id(color_dimmed));

    #   // Rinda header
    #   it.printf(0, 60, id(roboto_s), "Rinda");

    #   // Rinda icons
    #   it.image(0, 84, id(rinda_teams_meeting).state ? icon_phone : icon_phone_off, id(rinda_teams_meeting).state ? id(color_bright) : id(color_dimmed));
    #   it.image(32, 84, id(rinda_teams_microphone).state ? icon_microphone : icon_microphone_off, id(rinda_teams_microphone).state ? id(color_bright) : id(color_dimmed));
    #   it.image(64, 84, id(rinda_teams_video).state ? icon_webcam : icon_webcam_off, id(rinda_teams_video).state ? id(color_bright) : id(color_dimmed));
    #   it.image(96, 84, id(rinda_teams_sharing).state ? icon_projector_screen : icon_projector_screen_off, id(rinda_teams_sharing).state ? id(color_bright) : id(color_dimmed));

    # 2 columns - with strike-through icons
    # lambda: |-
    #   // Andrie header
    #   it.printf(0, 0, id(roboto_s), "Andrie");

    #   // Andrie icons
    #   it.image(0, 24, id(andrie_teams_meeting).state ? icon_phone : icon_phone_off, id(andrie_teams_meeting).state ? id(color_bright) : id(color_dimmed));
    #   it.image(30, 24, id(andrie_teams_microphone).state ? icon_microphone : icon_microphone_off, id(andrie_teams_microphone).state ? id(color_bright) : id(color_dimmed));
    #   it.image(0, 56, id(andrie_teams_video).state ? icon_webcam : icon_webcam_off, id(andrie_teams_video).state ? id(color_bright) : id(color_dimmed));
    #   it.image(30, 56, id(andrie_teams_sharing).state ? icon_projector_screen : icon_projector_screen_off, id(andrie_teams_sharing).state ? id(color_bright) : id(color_dimmed));
    #   it.image(0, 88, id(andrie_teams_blurred).state ? icon_blur : icon_blur_off, id(andrie_teams_blurred).state ? id(color_bright) : id(color_dimmed));
    #   it.image(30, 88, id(andrie_teams_recording).state ? icon_recording : icon_recording_off, id(andrie_teams_recording).state ? id(color_bright) : id(color_dimmed));

    #   // Rinda header
    #   it.printf(70, 0, id(roboto_s), "Rinda");

    #   // Rinda icons
    #   it.image(70, 24, id(rinda_teams_meeting).state ? icon_phone : icon_phone_off, id(rinda_teams_meeting).state ? id(color_bright) : id(color_dimmed));
    #   it.image(100, 24, id(rinda_teams_microphone).state ? icon_microphone : icon_microphone_off, id(rinda_teams_microphone).state ? id(color_bright) : id(color_dimmed));
    #   it.image(70, 56, id(rinda_teams_video).state ? icon_webcam : icon_webcam_off, id(rinda_teams_video).state ? id(color_bright) : id(color_dimmed));
    #   it.image(100, 56, id(rinda_teams_sharing).state ? icon_projector_screen : icon_projector_screen_off, id(rinda_teams_sharing).state ? id(color_bright) : id(color_dimmed));
    #   it.image(70, 88, id(rinda_teams_blurred).state ? icon_blur : icon_blur_off, id(rinda_teams_blurred).state ? id(color_bright) : id(color_dimmed));
    #   it.image(100, 88, id(rinda_teams_recording).state ? icon_recording : icon_recording_off, id(rinda_teams_recording).state ? id(color_bright) : id(color_dimmed));

    #   // Vertical line
    #   it.line(64, 0, 64, 116, id(color_dimmed));

    # 2 columns
    lambda: |-
      // Andrie header
      it.printf(2, 0, id(roboto_s), "Andrie");

      // Andrie icons
      it.image(0, 19, icon_phone, id(andrie_teams_meeting).state ? id(color_bright) : id(color_dimmed));
      it.image(30, 19, icon_microphone, id(andrie_teams_microphone).state ? id(color_bright) : id(color_dimmed));
      it.image(0, 48, icon_webcam, id(andrie_teams_video).state ? id(color_bright) : id(color_dimmed));
      it.image(30, 48, icon_projector_screen, id(andrie_teams_sharing).state ? id(color_bright) : id(color_dimmed));
      it.image(0, 77, icon_blur, id(andrie_teams_blurred).state ? id(color_bright) : id(color_dimmed));
      it.image(30, 77, icon_recording, id(andrie_teams_recording).state ? id(color_bright) : id(color_dimmed));

      // Rinda header
      it.printf(72, 0, id(roboto_s), "Rinda");

      // Rinda icons
      it.image(70, 19, icon_phone, id(rinda_teams_meeting).state ? id(color_bright) : id(color_dimmed));
      it.image(100, 19, icon_microphone, id(rinda_teams_microphone).state ? id(color_bright) : id(color_dimmed));
      it.image(70, 48, icon_webcam, id(rinda_teams_video).state ? id(color_bright) : id(color_dimmed));
      it.image(100, 48, icon_projector_screen, id(rinda_teams_sharing).state ? id(color_bright) : id(color_dimmed));
      it.image(70, 77, icon_blur, id(rinda_teams_blurred).state ? id(color_bright) : id(color_dimmed));
      it.image(100, 77, icon_recording, id(rinda_teams_recording).state ? id(color_bright) : id(color_dimmed));

      // Vertical line
      it.line(64, 0, 64, 106, id(color_dimmed));

      // Horizontal line
      it.line(0, 106, 128, 106, id(color_dimmed));

      // Temp & Humidity
      it.image(0, 110, icon_thermometer, id(color_bright));
      it.printf(20, 110, id(roboto_s), "%.1f", id(dht_temperature).state);
      it.image(70, 110, icon_water, id(color_bright));
      it.printf(90, 110, id(roboto_s), "%.1f", id(dht_humidity).state);


image:

  - file: mdi:phone
    id: icon_phone
    resize: 28x28
  - file: mdi:phone-off
    id: icon_phone_off
    resize: 28x28
  - file: mdi:microphone
    id: icon_microphone
    resize: 28x28
  - file: mdi:microphone-off
    id: icon_microphone_off
    resize: 28x28
  - file: mdi:webcam
    id: icon_webcam
    resize: 28x28
  - file: mdi:webcam-off
    id: icon_webcam_off
    resize: 28x28
  - file: mdi:projector-screen
    id: icon_projector_screen
    resize: 28x28
  - file: mdi:projector-screen-off
    id: icon_projector_screen_off
    resize: 28x28
  - file: mdi:blur
    id: icon_blur
    resize: 28x28
  - file: mdi:blur-off
    id: icon_blur_off
    resize: 28x28
  - file: mdi:record-circle-outline
    id: icon_recording
    resize: 28x28
  - file: mdi:power-off
    id: icon_recording_off
    resize: 28x28

  - file: mdi:thermometer
    id: icon_thermometer
    resize: 18x18
  - file: mdi:water
    id: icon_water
    resize: 18x18
